routes/web.php
<?php

use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserloginsController;
use App\Http\Controllers\GroupsController;
use App\Http\Controllers\AreasController;
use App\Http\Controllers\BrokersController;
use App\Http\Controllers\CropsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
    
});

Route::resource('userlogins', UserloginsController::class);
Route::resource('groups', GroupsController::class);
Route::resource('areas', AreasController::class);
Route::resource('brokers', BrokersController::class);
Route::get('brokers/getheadlist/{crop_id}', [BrokersController::class, 'getHeadList']);

Route::resource('crops', CropsController::class);

Route::get('/test',[TestController::class, 'index']);

app/Models/Crop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Crop extends Model
{
    use HasFactory;

    protected $table = 'crops';

    const CREATED_AT = 'created';
    const UPDATED_AT = 'modified';

    protected $fillable = ['name', 'details', 'sap_code', 'startdate', 'enddate', 
    'linkurl', 'createdBy', 'modifiedBy', 'max_per_day'];

}

app/Http/Controllers/CropsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Crop;

class CropsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $perPage = 25;
        $crops = Crop::orderBy('startdate','asc')->paginate($perPage);

        return view('admin.crops.index', compact('crops'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.crops.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = $request->all();
        Crop::create($requestData);

        return redirect('crops')->with('flash_message', ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $crop = Crop::findOrFail($id);
        return view('admin.crops.view', compact('crop'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $crop = Crop::findOrFail($id);
        return view('admin.crops.edit', compact('crop'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $requestData = $request->all();

        $crop = Crop::findOrFail($id);
        $crop->update($requestData);

        return redirect('crops')->with('flash_message', ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Crop::destroy($id);

        return redirect('crops')->with('flash_message', ' deleted!');
    }
}

resources/views/admin/crops/create.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('Crop Management') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('crops.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Create New Crop') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('crops.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="details"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Details') }}</label>

                                <div class="col-md-6">
                                    {!! Form::textarea('details', old('details'), ['class' => 'form-control', 'name' => 'name', 'required' => 'required', 'autocomplete' => 'name', 'autofocus' => 'autofocus']) !!}
                                    @error('details')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="sap_code"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Sap Code') }}</label>

                                <div class="col-md-6">
                                    <input id="sap_code" type="text"
                                        class="form-control @error('sap_code') is-invalid @enderror" name="sap_code"
                                        value="{{ old('sap_code') }}" required autocomplete="sap_code" autofocus>

                                    @error('sap_code')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="linkurl"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Link Url') }}</label>

                                <div class="col-md-6">
                                    <input id="linkurl" type="text"
                                        class="form-control @error('linkurl') is-invalid @enderror" name="linkurl"
                                        value="{{ old('linkurl') }}" required autocomplete="linkurl" autofocus>

                                    @error('linkurl')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="max_per_day"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Max Per Day') }}</label>

                                <div class="col-md-6">
                                    <input id="max_per_day" type="number"
                                        class="form-control @error('max_per_day') is-invalid @enderror" name="max_per_day"
                                        value="{{ old('max_per_day') }}" required autocomplete="max_per_day" autofocus>

                                    @error('max_per_day')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="startdate"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Start Date') }}</label>

                                <div class="col-md-6">
                                    {!! Form::date('startdate', null, old('startdate'), ['class' => 'form-control', 'name' => 'startdate', 'required' => 'required', 'autocomplete' => 'startdate', 'autofocus' => 'autofocus']) !!}

                                    @error('startdate')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="enddate"
                                    class="col-md-4 col-form-label text-md-right">{{ __('End Date') }}</label>

                                <div class="col-md-6">
                                    {!! Form::date('enddate', null, old('enddate'), ['class' => 'form-control', 'name' => 'enddate', 'required' => 'required', 'autocomplete' => 'enddate', 'autofocus' => 'autofocus']) !!}

                                    @error('enddate')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/crops/edit.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('Crop Management') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('crops.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Edit Crop') }}</div>

                <div class="card-body">
                    <form action="{{ route('crops.update',$crop->id) }}" method="POST">
                        @csrf

                        @method('PUT')

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $crop->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="detail" class="col-md-4 col-form-label text-md-right">{{ __('Details') }}</label>

                            <div class="col-md-6">
                                {!! Form::textarea('details', $crop->details, ['class'=>"form-control",'name'=>"name",'required'=>'required', 'autocomplete'=>"name", 'autofocus'=>'autofocus']) !!}
                                @error('detail')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="sap_code" class="col-md-4 col-form-label text-md-right">{{ __('Sap Code') }}</label>

                            <div class="col-md-6">
                                <input id="sap_code" type="text" class="form-control @error('sap_code') is-invalid @enderror" name="sap_code" value="{{ $crop->sap_code }}" required autocomplete="sap_code" autofocus>

                                @error('sap_code')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="linkurl" class="col-md-4 col-form-label text-md-right">{{ __('Link Url') }}</label>

                            <div class="col-md-6">
                                <input id="linkurl" type="text" class="form-control @error('linkurl') is-invalid @enderror" name="linkurl" value="{{ $crop->linkurl }}" required autocomplete="linkurl" autofocus>

                                @error('linkurl')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="max_per_day" class="col-md-4 col-form-label text-md-right">{{ __('Max Per Day') }}</label>

                            <div class="col-md-6">
                                <input id="max_per_day" type="number" class="form-control @error('max_per_day') is-invalid @enderror" name="max_per_day" value="{{ $crop->max_per_day }}" required autocomplete="max_per_day" autofocus>

                                @error('max_per_day')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="startdate" class="col-md-4 col-form-label text-md-right">{{ __('Start Date') }}</label>

                            <div class="col-md-6">
                                {!! Form::date('startdate',  $crop->startdate, ['class'=>"form-control",'name'=>"startdate",'required'=>'required', 'autocomplete'=>"startdate", 'autofocus'=>'autofocus']) !!}
                                @error('startdate')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="enddate" class="col-md-4 col-form-label text-md-right">{{ __('End Date') }}</label>

                            <div class="col-md-6">
                                {!! Form::date('enddate',  $crop->enddate, ['class'=>"form-control",'name'=>"enddate",'required'=>'required', 'autocomplete'=>"enddate", 'autofocus'=>'autofocus']) !!}

                                @error('enddate')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/crops/index.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('Crop Management') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><a class="btn btn-success" href="{{ route('crops.create') }}"> Create New
                            Crop</a></div>

                    <div class="card-body">
                        <div class="pull-right">

                        </div>
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>SAP CODE</th>
                                <th>Name</th>
                                <th>Link</th>
                                <th>Timeline</th>
                                <th></th>
                            </tr>
                            @foreach ($crops as $crop)
                                <tr>
                                    <td>{{ $crop->sap_code }}</td>
                                    <td>{{ $crop->name }}</td>
                                    <td>{{ $crop->linkurl }}</td>                                    
                                    <td>{{ $crop->startdate }} / {{ $crop->enddate }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('crops.show', $crop->id) }}">Show</a>
                                        <a class="btn btn-primary" href="{{ route('crops.edit', $crop->id) }}">Edit</a>
                                        <form action="{{ route('crops.destroy', $crop->id) }}" method="POST">

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/admin/crops/view.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('Crop Management') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('crops.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('View Crop') }}</div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">

                            <tr>
                                <th>Name</th>
                                <td>{{ $crop->name }}</td>
                            </tr>
                            <tr>
                                <th>Details</th>
                                <td>{{ $crop->details }}</td>
                            </tr>
                            <tr>
                                <th>Sap Code</th>
                                <td>{{ $crop->sap_code }}</td>
                            </tr>
                            <tr>
                                <th>Link Url</th>
                                <td>{{ $crop->linkurl }}</td>
                            </tr>

                            <tr>
                                <th>Max Per Day</th>
                                <td>{{ $crop->max_per_day }}</td>
                            </tr>
                            <tr>
                                <th>Start Date</th>
                                <td>{{ $crop->startdate }}</td>
                            </tr>

                            <tr>
                                <th>End Date</th>
                                <td>{{ $crop->enddate }}</td>
                            </tr>
                            <tr>
                                <th>Action</th>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('crops.edit', $crop->id) }}">Edit</a>
                                    <form action="{{ route('crops.destroy', $crop->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection