routes/web.php
<?php

use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserloginsController;
use App\Http\Controllers\GroupsController;
use App\Http\Controllers\AreasController;
use App\Http\Controllers\BrokersController;
use App\Http\Controllers\CropsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
    
});

Route::resource('userlogins', UserloginsController::class);
Route::resource('groups', GroupsController::class);
Route::resource('areas', AreasController::class);
Route::resource('brokers', BrokersController::class);
Route::get('brokers/getheadlist/{crop_id}', [BrokersController::class, 'getHeadList']);

Route::resource('crops', CropsController::class);

Route::get('/test',[TestController::class, 'index']);

app/Http/Controllers/UserloginsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\UserAe;

class UserloginsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $perPage = 25;
        $users = User::latest()->paginate($perPage);

        return view('admin.userlogins.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $useraelist = UserAe::pluck('username','id');
        return view('admin.userlogins.create',compact('useraelist'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requestData = $request->all();

        $userae = UserAe::findOrFail($requestData['user_ae_id']);

        $requestData['group_id'] = $userae->group->id;

        User::create($requestData);

        return redirect('userlogins')->with('flash_message', ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $userlogin = User::findOrFail($id);
        return view('admin.userlogins.view', compact('userlogin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $userlogin = User::findOrFail($id);
        $useraelist = UserAe::pluck('username', 'id');
        return view('admin.userlogins.edit', compact('userlogin', 'useraelist'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $requestData = $request->all();

        $userae = UserAe::findOrFail($requestData['user_ae_id']);

        $requestData['group_id'] = $userae->group->id;

        $userlogin = User::findOrFail($id);
        $userlogin->update($requestData);

        return redirect('userlogins')->with('flash_message', ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return redirect('userlogins')->with('flash_message', ' deleted!');
    }
}

resources/views/admin/userlogins/create.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('User Management') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('userlogins.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Create New Users') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('userlogins.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="username"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                <div class="col-md-6">
                                    <input id="username" type="text"
                                        class="form-control @error('username') is-invalid @enderror" name="username"
                                        value="{{ old('username') }}" required autocomplete="username" autofocus>

                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                    class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                        name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                        class="form-control @error('password') is-invalid @enderror" name="password"
                                        required autocomplete="new-password">

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                        name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="user_ae_id"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Link User') }}</label>

                                <div class="col-md-6">

                                    {!! Form::select('user_ae_id', $useraelist, null, ['class' => 'form-control', 'id' => 'user_ae_id']) !!}

                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/userlogins/edit.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('User Management') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('userlogins.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Create New Users') }}</div>

                    <div class="card-body">
                        <form action="{{ route('userlogins.update', $userlogin->id) }}" method="POST">
                            @csrf

                            @method('PUT')

                            <div class="form-group row">
                                <label for="username"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                <div class="col-md-6">
                                    <input id="username" type="text"
                                        class="form-control @error('username') is-invalid @enderror" name="username"
                                        value="{{ $userlogin->username }}" required autocomplete="username" autofocus>

                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ $userlogin->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                    class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                        name="email" value="{{ $userlogin->email }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                        class="form-control @error('password') is-invalid @enderror" name="password"
                                        required autocomplete="new-password">

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                        name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="user_ae_id"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Link User') }}</label>

                                <div class="col-md-6">

                                    {!! Form::select('user_ae_id', $useraelist, $userlogin->ae_user_id, ['class' => 'form-control', 'id' => 'user_ae_id']) !!}

                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/userlogins/index.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('User Management') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><a class="btn btn-success" href="{{ route('userlogins.create') }}"> Create
                            New Users</a></div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>Username</th>
                                <th>Name</th>
                                <th>Group</th>
                                <th>Link</th>
                                <th></th>
                            </tr>
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->group->name ?? '' }}</td>
                                    <td>{{ $user->userae->username ?? '' }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('userlogins.show', $user->id) }}">Show</a>
                                        <a class="btn btn-primary"
                                            href="{{ route('userlogins.edit', $user->id) }}">Edit</a>
                                        <form action="{{ route('userlogins.destroy', $user->id) }}" method="POST">

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/admin/userlogins/view.blade.php
@extends('templates.mazer')

@section('content')

    <div class="page-heading">
        <h3>{{ __('User Management') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('userlogins.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('View User Login') }}</div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>Username</th>
                                <td>{{ $userlogin->username }}</td>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <td>{{ $userlogin->name }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ $userlogin->email }}</td>
                            </tr>
                            <tr>
                                <th>Group</th>
                                <td>{{ $userlogin->group->name ?? '' }}</td>
                            </tr>
                            <tr>
                                <th>Link</th>
                                <td>{{ $userlogin->userae->username ?? '' }}</td>
                            </tr>
                            <tr>
                                <th>Action</th>
                                <td>
                                    <a class="btn btn-primary"
                                        href="{{ route('userlogins.edit', $userlogin->id) }}">Edit</a>
                                    <form action="{{ route('userlogins.destroy', $userlogin->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection